In [2]:
import numpy as np

In [3]:
arr=np.array([10,20,30,40,50])

In [4]:
print("Numpy array is ",arr)

Numpy array is  [10 20 30 40 50]


In [5]:
print("First element:",arr[0])

First element: 10


In [6]:
print("Last element:",arr[-1])

Last element: 50


In [7]:
print(arr[0:3])

[10 20 30]


In [8]:
print(arr[-1:])

[50]


In [12]:
print(arr[-3:])

[30 40 50]


In [13]:
print("Add 5:",arr+5)

Add 5: [15 25 35 45 55]


In [14]:
print("Multiply by 5:",arr*5)

Multiply by 5: [ 50 100 150 200 250]


In [15]:
print("Sum:",np.sum(arr))

Sum: 150


In [16]:
print("Mean:",np.mean(arr))

Mean: 30.0


In [17]:
print("Maximum:",np.max(arr))

Maximum: 50


In [18]:
reshape=arr.reshape(5,1)
print(reshape)

[[10]
 [20]
 [30]
 [40]
 [50]]


In [19]:
import pandas as pd

In [21]:
data={ "Name":["Rahul","Mbappe","Cristiano"],
      "Marks":[11,22,7],
      "Branch":["CSE","ECE","FOOTBALL"]}

In [22]:
df=pd.DataFrame(data)
print(df)

        Name  Marks    Branch
0      Rahul     11       CSE
1     Mbappe     22       ECE
2  Cristiano      7  FOOTBALL


In [23]:
print(df["Marks"])

0    11
1    22
2     7
Name: Marks, dtype: int64


In [24]:
print(df["Name"])

0        Rahul
1       Mbappe
2    Cristiano
Name: Name, dtype: object


In [26]:
print("First row using row:")
print(df.iloc[0])

First row using row:
Name      Rahul
Marks        11
Branch      CSE
Name: 0, dtype: object


In [27]:
print("First person marks:",df.iloc[0,1])

First person marks: 11


In [29]:
print("Row slicing of first two rows:")
print(df.iloc[0:2])

Row slicing of first two rows:
     Name  Marks Branch
0   Rahul     11    CSE
1  Mbappe     22    ECE


In [32]:
print("Both row and coln slicing")
print(df.iloc[0:3,[0,1]])

Both row and coln slicing
        Name  Marks
0      Rahul     11
1     Mbappe     22
2  Cristiano      7


In [35]:
print("Filtering:")
res=df[df["Marks"]>9]
print("Students with marks greater than 9:")
print(res)

Filtering:
Students with marks greater than 9:
     Name  Marks Branch
0   Rahul     11    CSE
1  Mbappe     22    ECE


In [ ]:
arr1=np.array([10,20],[30,40])
print(np.shape(arr1))